export const posts = [
  {
    id: 1,
    url: "/posts1.webp",
    title: "PHOTOGRAPHY",
    text: "HELMUT LANG CELEBRATES TAXI DRIVERS WORLDWIDE IN LATEST CAMPAIGN",
    link: "BY ALESSANDRA ORTIZ",
  },
  {
    id: 2,
    url: "/posts2.webp",
    title: "PHOTOGRAPHY",
    text: "BOWLCUT LAUNCH A NEW SUMMER COLLECTION THAT PAYS HOMAGE TO “UK LEGENDS”",
    link: "BY ROSANNA ONDRICKA",
  },
  {
    id: 3,
    url: "/posts3.webp",
    title: "PHOTOGRAPHY",
    text: "THOUSANDS OF PREVIOUSLY UNSEEN PHOTOGRAPHS BY ANDY WARHOL WILL BE MADE PUBLIC THIS AUTUMN",
    link: "BY ANNIE LUEILWITZ",
  },
  {
    id: 4,
    url: "/posts4.webp",
    title: "PHOTOGRAPHY",
    text: "HELMUT LANG CELEBRATES TAXI DRIVERS WORLDWIDE IN LATEST CAMPAIGN",
    link: "BY ALESSANDRA ORTIZ",
  },
  {
    id: 5,
    url: "/posts5.webp",
    title: "PHOTOGRAPHY",
    text: "LONDON-BASED YINKA ILORI’S STORYTELLING FURNITURE",
    link: "BY ANNIE LUEILWITZ",
  },
  {
    id: 6,
    url: "/posts6.webp",
    title: "PHOTOGRAPHY",
    text: "ANONYMOUS ISRAELI ART COLLECTIVE BROKEN FINGAZ DIRECT MUSIC VIDEO FOR U2 AND BECK",
    link: "BYALESSANDRA ORTIZ",
  },
  {
    id: 7,
    url: "/posts7.webp",
    title: "PHOTOGRAPHY",
    text: "SUZANNE SAROFF’S METICULOUSLY ARRANGED PHOTOGRAPHS ALTER PERCEPTIONS",
    link: "BYALESSANDRA ORTIZ",
  },
  {
    id: 8,
    url: "/posts8.webp",
    title: "PHOTOGRAPHY",
    text: "ANU AMBASNA’S PLAYFUL ILLUSTRATIONS CELEBRATE CLUB CULTURE, BROWN BODIES AND PERFECT PAUNCHES",
    link: "BYALESSANDRA ORTIZ",
  },
  {
    id: 9,
    url: "/posts9.webp",
    title: "PHOTOGRAPHY",
    text: "RUDY GUEDJ’S DESIGN WORK SITS BETWEEN “FIGURATIVE MOTIVES AND THEIR ABSTRACTED REPRESENTATIONS”",
    link: "BYALESSANDRA ORTIZ",
  },
  {
    id: 10,
    url: "/posts10.webp",
    title: "PHOTOGRAPHY",
    text: "HOW ALEX PRAGER MADE THE WORLD STOP AND STARE",
    link: "BYALESSANDRA ORTIZ",
  },
  {
    id: 11,
    url: "/posts11.webp",
    title: "PHOTOGRAPHY",
    text: "NEW PLATFORM HOLDFRAME OFFERS ANIMATORS’ FULL PROJECT FILES FOR OTHERS TO DOWNLOAD AND EXPLORE",
    link: "BYALESSANDRA ORTIZ",
  },
  {
    id: 12,
    url: "/posts12.webp",
    title: "PHOTOGRAPHY",
    text: "NO BALLS, ALL BOOKS: IT’S JULY THINGS!",
    link: "BYALESSANDRA ORTIZ",
  },
  {
    id: 13,
    url: "/posts13.webp",
    title: "PHOTOGRAPHY",
    text: "ANU AMBASNA’S PLAYFUL ILLUSTRATIONS CELEBRATE CLUB CULTURE, BROWN BODIES AND PERFECT PAUNCHES",
    link: "BYALESSANDRA ORTIZ",
  },
  {
    id: 14,
    url: "/posts14.webp",
    title: "PHOTOGRAPHY",
    text: "ANU AMBASNA’S PLAYFUL ILLUSTRATIONS CELEBRATE CLUB CULTURE, BROWN BODIES AND PERFECT PAUNCHES",
    link: "BYALESSANDRA ORTIZ",
  },
  {
    id: 15,
    url: "/posts15.webp",
    title: "PHOTOGRAPHY",
    text: "NEED A GUIDE TO LA’S GRAPHIC DESIGN SCENE? SHOPLIFTERS’ NEW ISSUE HAS GOT YOUR BACK",
    link: "BYALESSANDRA ORTIZ",
  },
  {
    id: 16,
    url: "/posts16.webp",
    title: "PHOTOGRAPHY",
    text: "A BRIEF HISTORY OF THE FIFA WORLD CUP LOGO",
    link: "BYALESSANDRA ORTIZ",
  },
];

export const featured = [
  {
    id: 1,
    url: "/featured1.webp",
    title: "GRAPHIC DESIGN",
    text: "A BRIEF HISTORY OF THE FIFA WORLD CUP LOGO",
    link: "BY CLEM ONOJEGHUO",
  },
  {
    id: 2,
    url: "/featured2.webp",
    title: "GRAPHIC DESIGN",
    text: "NEED A GUIDE TO LA’S GRAPHIC DESIGN SCENE? SHOPLIFTERS’ NEW ISSUE HAS GOT YOUR BACK",
    link: "BY CLEM ONOJEGHUO",
  },
  {
    id: 3,
    url: "/featured3.webp",
    title: "GRAPHIC DESIGN",
    text: "FRED ROWSON DIRECTS FILM FOR YEARS AND YEARS",
    link: "BY CLEM ONOJEGHUO",
  },
  {
    id: 4,
    url: "/featured4.webp",
    title: "GRAPHIC DESIGN",
    text: "M&C SAATCHI AND FONTSMITH COLLABORATE ON FONT COLLECTION FOR HOUSE OF ST BARNABAS",
    link: "BY CLEM ONOJEGHUO",
  },
];

export const team = [
  {
    id: 1,
    title: "Simeon Peterson",
    text: "COFOUNDER, EDITOR IN CHIEF",
    url: "/team1.webp",
  },
  {
    id: 2,
    title: "Simeon Brekke",
    text: "COFOUNDER, PARTNER",
    url: "/team2.webp",
  },
  {
    id: 3,
    title: "Annie Lueilwitz",
    text: "MANAGING EDITOR",
    url: "/team3.webp",
  },
  {
    id: 4,
    title: "Reta Torphy",
    text: "MANAGING EDITOR",
    url: "/team4.webp",
  },
  {
    id: 5,
    title: "Leo Bartell",
    text: "EDITOR",
    url: "/team5.webp",
  },
  {
    id: 6,
    title: "Clem Onojeghuo",
    text: "SENIOR WRITER",
    url: "/team6.webp",
  },
  {
    id: 7,
    title: "Michal Legros",
    text: "SENIOR WRITER",
    url: "/team7.webp",
  },
  {
    id: 8,
    title: "Rosanna Ondricka",
    text: "WRITER",
    url: "/team8.webp",
  },
  {
    id: 9,
    title: "Alessandra Ortiz",
    text: "WRITER",
    url: "/team9.webp",
  },
  {
    id: 10,
    title: "Coby Gottlieb",
    text: "WRITER",
    url: "/team10.webp",
  },
];
