import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { tenor_sans, libre_franklin, source_serif } from "@/utils/fonts";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${tenor_sans.variable} ${libre_franklin.variable} ${source_serif.variable}`}
    >
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
